# Generated by Django 2.1.4 on 2019-01-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='content',
            field=models.CharField(max_length=140, verbose_name='content'),
        ),
    ]
