# Generated by Django 2.2.2 on 2019-07-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20190103_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='file',
            field=models.FileField(null=True, upload_to='media/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
    ]
