# Generated by Django 2.2.2 on 2019-07-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_timeline_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='添付ファイル'),
        ),
    ]
