# Generated by Django 2.2.2 on 2019-07-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20190720_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='添付ファイル'),
        ),
    ]
